### ISSUE TITLE
[[ debug output ]] error while signing in

### ISSUE THREAD

**Issue by soapdog** [ssb-ngi-pointer/ssb-room2-check#2]
After executing the sign-in command on the terminal, I got a URL that should be valid for 5 minutes. When I clicked it, I got an error 500:

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/23247/115714564-260cc300-a36f-11eb-8033-a41c56482980.png">

The terminal showed a bunch of PacketStream errors:

```
Exception thrown by PacketStream substream end handler Error: unexpected end of parent stream
    at PacketStream.destroy (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/packet-stream/index.js:64:7)
    at PacketStream.write (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/packet-stream/index.js:126:41)
    at source (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/muxrpc/pull-weird.js:43:24)
    at /Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-goodbye/endable.js:6:7
    at /Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-through/index.js:31:16
    at /Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-stream/throughs/through.js:16:14
    at cancel (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-abortable/index.js:13:5)
    at Function.reader.abort (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-abortable/index.js:47:5)
    at abort (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-inactivity/index.js:33:17)
    at Timeout.<anonymous> (/Users/agarzia/.npm/_npx/49d5dc091f17ffb4/node_modules/pull-inactivity/index.js:40:7)
Error: unexpected end of parent stream
...
```

**Comment by staltz** [comment]
The unexpected end of parent stream is something else, and we began handling it correctly in ssb-room-client. The HTML-rendered error is maybe something else, not sure.
